version: "3.9"

services:
  # --------------------
  # Production Postgres
  # --------------------
  db_prod:
    image: postgres:15.13
    container_name: db_prod
    environment:
      POSTGRES_DB: prod_db
      POSTGRES_USER: prod_user
      POSTGRES_PASSWORD: prod_pass
    ports:
      - "5435:5432"
    volumes:
      - db_prod_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prod_user -d prod_db"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  # --------------------
  # Redis Service
  # --------------------
  redis_prod:
    image: redis:7.0
    container_name: redis_prod
    ports:
      - "6381:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --------------------
  # Django Web
  # --------------------
  web_prod:
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: pointless_impressions_web_prod
    env_file:
      - .env.production
    ports:
      - "8002:8000"
    volumes:
      - .:/app
    depends_on:
      db_prod:
        condition: service_healthy
      redis_prod:
        condition: service_healthy
    restart: no
    command: /app/pointless_impressions_src/production-entrypoint.sh

volumes:
  db_prod_data:
