# Generated by Django 5.2.7 on 2025-11-13 10:59

import django.db.models.deletion
import pointless_impressions_src.order.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artwork', '0017_alter_artworkreview_artwork_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the order', primary_key=True, serialize=False)),
                ('order_number', models.CharField(default=pointless_impressions_src.order.models.generate_order_number, help_text='Unique order number', max_length=50, unique=True)),
                ('geust_email', models.EmailField(blank=True, help_text='Email of guest user (if applicable)', max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the order was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the order was last updated')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount for the order', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of the order', max_length=20)),
                ('shipping_address', models.TextField(blank=True, help_text='Shipping address for the order')),
                ('billing_address', models.TextField(blank=True, help_text='Billing address for the order')),
                ('staff_updated', models.BooleanField(default=False, help_text='Flag to indicate if staff updated the order')),
                ('staff_member', models.ForeignKey(blank=True, help_text='Staff member who updated the order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_updated_orders', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='User who placed the order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of the artwork ordered')),
                ('notes', models.TextField(blank=True, help_text='Additional notes for this order item')),
                ('price_at_purchase', models.DecimalField(decimal_places=2, help_text='Price of the artwork at the time of purchase', max_digits=10)),
                ('framing_condition', models.CharField(blank=True, help_text='Framing condition selected for the artwork', max_length=255)),
                ('image_url_at_purchase', models.CharField(blank=True, help_text='URL of the artwork image at the time of purchase', max_length=1024, null=True)),
                ('artwork', models.ForeignKey(help_text='The artwork associated with this order item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='artwork.artwork')),
                ('order', models.ForeignKey(help_text='The order this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
            ],
        ),
    ]
