# Generated by Django 5.2.7 on 2025-11-13 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='geust_email',
            new_name='guest_email',
        ),
    ]
