# Generated by Django 5.2.7 on 2025-11-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_geust_email_order_guest_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='staff_notes',
            field=models.TextField(blank=True, help_text='Notes added by staff regarding the order', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_name',
            field=models.CharField(default='', help_text='Name of the artwork at the time of purchase', max_length=255),
        ),
    ]
