# Generated by Django 5.2.7 on 2025-11-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_staff_notes_orderitem_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_phone',
            field=models.CharField(blank=True, help_text='Phone number of guest user (if applicable)', max_length=20, null=True),
        ),
    ]
