# Generated by Django 5.2.7 on 2025-11-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_guest_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_access_code',
            field=models.UUIDField(blank=True, editable=False, help_text='Unique access code for guest users to view their order', null=True, unique=True),
        ),
    ]
