# Generated by Django 5.2.7 on 2025-11-13 20:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_guest_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='guest_access_code',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='Unique access code for guest users to view their order', null=True, unique=True),
        ),
    ]
