# Generated by Django 5.2.7 on 2025-11-13 20:10

import pointless_impressions_src.order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_guest_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='guest_access_code',
            field=models.CharField(blank=True, default=pointless_impressions_src.order.models.generate_guest_access_code, editable=False, help_text='Unique access code for guest users to view their order', max_length=50, null=True, unique=True),
        ),
    ]
