# Generated by Django 5.2.7 on 2025-11-17 22:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_guest_access_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address_line_1',
            field=models.CharField(blank=True, help_text='Address line 1 for billing', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address_line_2',
            field=models.CharField(blank=True, help_text='Address line 2 for billing (optional)', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_city',
            field=models.CharField(blank=True, help_text='City for billing', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_country',
            field=models.CharField(blank=True, help_text='Country for billing', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_county',
            field=models.CharField(blank=True, help_text='County for billing (optional)', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_first_name',
            field=models.CharField(blank=True, help_text='First name for billing', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_last_name',
            field=models.CharField(blank=True, help_text='Last name for billing', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_postcode',
            field=models.CharField(blank=True, help_text='Postcode for billing', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Delivery fee for the order', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount for the order', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address_line_1',
            field=models.CharField(blank=True, help_text='Address line 1 for shipping', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address_line_2',
            field=models.CharField(blank=True, help_text='Address line 2 for shipping (optional)', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(blank=True, help_text='City for shipping', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_country',
            field=models.CharField(blank=True, help_text='Country for shipping', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_county',
            field=models.CharField(blank=True, help_text='County for shipping (optional)', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_first_name',
            field=models.CharField(blank=True, help_text='First name for shipping', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_last_name',
            field=models.CharField(blank=True, help_text='Last name for shipping', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_postcode',
            field=models.CharField(blank=True, help_text='Postcode for shipping', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal amount before delivery and taxes', max_digits=10),
        ),
    ]
