# Generated by Django 5.2.7 on 2025-11-13 21:18

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_guest_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='guest_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Phone number of guest user (if applicable)', max_length=128, null=True, region=None),
        ),
    ]
