# Generated by Django 5.2.7 on 2025-11-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_order_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, help_text='Unique Square payment ID associated with the order', max_length=255, null=True, unique=True),
        ),
    ]
