# Generated by Django 5.2.7 on 2025-11-19 17:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecovery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the payment recovery record', primary_key=True, serialize=False)),
                ('payment_id', models.CharField(help_text='Unique Square payment ID associated with the recovery', max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to be recovered', max_digits=10)),
                ('currency', models.CharField(default='GBP', help_text='Currency of the amount', max_length=10)),
                ('buyer_email', models.EmailField(help_text='Email of the buyer', max_length=254)),
                ('buyer_phone', models.CharField(blank=True, help_text='Phone number of the buyer (optional)', max_length=20, null=True)),
                ('shipping_address', models.JSONField()),
                ('billing_address', models.JSONField()),
                ('cart_snapshot', models.JSONField(blank=True, help_text='Snapshot of the cart items at the time of payment failure', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes regarding the payment recovery', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the payment recovery record was created')),
                ('processed', models.BooleanField(default=False, help_text='Flag to indicate if the payment recovery has been processed')),
            ],
        ),
    ]
