# Generated by Django 5.2.7 on 2025-10-31 12:05

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')

    groups_to_create = ['Owner', 'Manager', 'Employee']

    for group_name in groups_to_create:
        group, created = Group.objects.get_or_create(name=group_name)


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_delete_customrole_customuser_is_employee'),
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
