# Generated by Django 5.2.7 on 2025-10-31 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photo', '0007_remove_photo_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=255)),
                ('sort_code', models.CharField(blank=True, max_length=10)),
                ('account_number', models.CharField(blank=True, max_length=20)),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('swift_bic', models.CharField(blank=True, max_length=11, verbose_name='SWIFT/BIC')),
                ('billing_address_line_1', models.CharField(max_length=255)),
                ('billing_address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_city', models.CharField(max_length=100)),
                ('billing_county', models.CharField(blank=True, max_length=100)),
                ('billing_postcode', models.CharField(max_length=20)),
                ('billing_country', models.CharField(max_length=100)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='profiles.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Label for the address (e.g., Home, Work)', max_length=50)),
                ('address_type', models.CharField(choices=[('SHIPPING', 'Shipping'), ('BILLING', 'Billing')], default='SHIPPING', max_length=10)),
                ('name_addressee', models.CharField(max_length=255)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='profiles.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor_customer_id', models.CharField(max_length=255)),
                ('payment_method_id', models.CharField(max_length=255, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('last_four_digits', models.CharField(max_length=4)),
                ('expiry_month', models.PositiveSmallIntegerField()),
                ('expiry_year', models.PositiveSmallIntegerField()),
                ('is_default', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='profiles.customer')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='photo.photo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
