# Generated by Django 5.2.7 on 2025-11-16 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_address_customer_address_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='profiles.userprofile'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='profiles.userprofile'),
        ),
        migrations.AlterField(
            model_name='staffrole',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_roles', to='profiles.userprofile'),
        ),
    ]
