# Generated by Django 5.2.7 on 2025-11-16 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_staffrole_role_friendly_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_artists', to='profiles.staffrole'),
        ),
        migrations.AddField(
            model_name='artist',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='portfolio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
