# Generated by Django 5.2.7 on 2025-11-16 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_artist_approved_by_artist_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='profiles.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='receive_newsletter',
            field=models.BooleanField(default=False, help_text='Indicates whether the customer wants to receive the newsletter.'),
        ),
    ]
