# Generated by Django 5.2.7 on 2025-11-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_address_user_profile_address_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='social_links',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
