# Generated by Django 5.2.7 on 2025-11-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_artist_social_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_type',
        ),
        migrations.AddField(
            model_name='address',
            name='is_billing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='is_shipping',
            field=models.BooleanField(default=False),
        ),
    ]
