# Generated by Django 5.2.7 on 2025-11-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_remove_address_address_type_address_is_billing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='paymentinfo',
            name='customer',
        ),
        migrations.DeleteModel(
            name='BankDetails',
        ),
        migrations.DeleteModel(
            name='PaymentInfo',
        ),
    ]
