# Generated by Django 5.2.7 on 2025-10-25 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='image',
        ),
    ]
