# Generated by Django 5.2.7 on 2025-10-25 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_alter_artwork_name_alter_category_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkFramingCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(max_length=255)),
                ('condition_description', models.TextField()),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='framing_condition', to='artwork.artwork')),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='selected_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artwork_condition', to='artwork.artworkframingcondition'),
        ),
    ]
