# Generated by Django 5.2.7 on 2025-10-25 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0004_artworkframingcondition_artwork_selected_condition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ArtworkCategory',
        ),
    ]
