# Generated by Django 5.2.7 on 2025-10-25 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0005_rename_category_artworkcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artworkframingcondition',
            name='artwork',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='selected_condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artwork_condition', to='artwork.artworkframingcondition'),
        ),
    ]
