# Generated by Django 5.2.7 on 2025-10-27 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0006_remove_artworkframingcondition_artwork_and_more'),
        ('photo', '0006_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='main_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_for_artwork', to='photo.photo'),
        ),
    ]
