# Generated by Django 5.2.7 on 2025-10-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0007_artwork_main_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
