# Generated by Django 5.2.7 on 2025-10-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0008_artworkcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkframingcondition',
            name='condition_friendly_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artworkframingcondition',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
