# Generated by Django 5.2.7 on 2025-11-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0011_artwork_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='selected_condition',
        ),
        migrations.AddField(
            model_name='artwork',
            name='selected_conditions',
            field=models.ManyToManyField(help_text='The set of framing/condition options available for customer selection.', related_name='available_conditions', to='artwork.artworkframingcondition'),
        ),
    ]
