# Generated by Django 5.2.7 on 2025-11-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0012_remove_artwork_selected_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
