# Generated by Django 5.2.7 on 2025-11-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0014_artworkreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkreview',
            name='review_title',
            field=models.CharField(default='Review', max_length=255),
        ),
    ]
