# Generated by Django 5.2.7 on 2025-11-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0015_artworkreview_review_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkreview',
            name='rating',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='artworkreview',
            name='review_text',
            field=models.TextField(default=''),
        ),
    ]
