# Generated by Django 5.2.7 on 2025-11-12 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0016_alter_artworkreview_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkreview',
            name='artwork',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='artwork.artwork'),
        ),
        migrations.AlterField(
            model_name='artworkreview',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_written', to=settings.AUTH_USER_MODEL),
        ),
    ]
