# Generated by Django 5.2.7 on 2025-11-18 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0017_alter_artworkreview_artwork_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtworkReview',
        ),
    ]
