# Generated by Django 5.2.7 on 2025-10-25 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0006_remove_artworkframingcondition_artwork_and_more'),
        ('photo', '0004_alter_photo_description_alter_photo_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
        migrations.AddField(
            model_name='photo',
            name='asset_identifier',
            field=models.CharField(blank=True, help_text="Identifier for site assets (e.g., 'logo_main', 'banner_home')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_type',
            field=models.CharField(choices=[('artwork', 'Artwork Image'), ('profile', 'Profile Picture'), ('site_asset', 'Site Asset (Logo, Banner, etc.)')], default='artwork', help_text='Type of photo being uploaded', max_length=20),
        ),
        migrations.AddField(
            model_name='photo',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='User who uploaded this photo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photo',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photo',
            name='artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='artwork.artwork'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['photo_type'], name='photo_photo_photo_t_ffa5cd_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['asset_identifier'], name='photo_photo_asset_i_5c4af1_idx'),
        ),
    ]
