# Generated by Django 5.2.7 on 2025-10-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_alter_photo_options_photo_asset_identifier_and_more'),
    ]
