# Generated by Django 5.2.7 on 2025-10-27 14:41

import pointless_impressions_src.photo.models
import pointless_impressions_src.photo.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_alter_photo_options_photo_asset_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(storage=pointless_impressions_src.photo.storage.OverwriteStorage(), upload_to=pointless_impressions_src.photo.models.artwork_image_path),
        ),
    ]
