# Generated by Django 5.2.7 on 2025-10-31 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_alter_photo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='account',
        ),
    ]
