# Generated by Django 5.2.7 on 2025-11-09 16:00

import pointless_impressions_src.photo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0008_alter_photo_image'),
    ]
