# Generated by Django 5.2.7 on 2025-11-17 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0010_alter_photo_image'),
        ('profiles', '0008_remove_address_user_profile_address_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='profiles.userprofile'),
        ),
    ]
