# Generated by Django 5.2.7 on 2025-11-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0016_alter_artworkreview_rating_and_more'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'artwork', 'framing_condition')},
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['framing_condition'], name='checkout_ca_framing_5f24c5_idx'),
        ),
    ]
