# Generated by Django 5.2.7 on 2025-11-12 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0017_alter_artworkreview_artwork_and_more'),
        ('checkout', '0004_remove_cart_checkout_ca_uuid_92357b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Associated user (null for anonymous carts)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='artwork',
            field=models.ForeignKey(help_text='Artwork in cart', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='artwork.artwork'),
        ),
    ]
