# Generated by Django 5.2.7 on 2025-11-13 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artwork', '0017_alter_artworkreview_artwork_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='Unique identifier for cart (used for anonymous users)', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When cart was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When cart was last modified')),
                ('expires_at', models.DateTimeField(help_text='When cart will expire (30 days from update)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether cart is active')),
                ('user', models.OneToOneField(blank=True, help_text='Associated user (null for anonymous carts)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of units')),
                ('notes', models.TextField(blank=True, help_text='Special requests or notes (max 500 chars)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When item was added to cart')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When item was last updated')),
                ('artwork', models.ForeignKey(help_text='Artwork in cart', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='artwork.artwork')),
                ('cart', models.ForeignKey(help_text='Parent cart', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart')),
                ('framing_condition', models.ForeignKey(blank=True, help_text="Selected framing condition from artwork's selected_conditions", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='artwork.artworkframingcondition')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['session_id'], name='cart_cart_session_f55f25_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user'], name='cart_cart_user_id_b645f9_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['expires_at'], name='cart_cart_expires_8a239f_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart'], name='cart_cartit_cart_id_4fb076_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['artwork'], name='cart_cartit_artwork_1a0fee_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['framing_condition'], name='cart_cartit_framing_f2df4d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'artwork', 'framing_condition')},
        ),
    ]
