# Generated by Django 5.2.7 on 2025-11-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_cartitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.CharField(db_index=True, help_text='Unique identifier for cart (used for anonymous users)', max_length=255, unique=True),
        ),
    ]
