# Generated by Django 5.2.7 on 2025-11-12 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_cart_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cart',
            name='checkout_ca_uuid_92357b_idx',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='uuid',
            new_name='session_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='data',
            field=models.JSONField(default=dict, help_text='Stores cart data as a JSON object.'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['session_id'], name='checkout_ca_session_9171a2_idx'),
        ),
    ]
