# Generated by Django 5.2.7 on 2025-11-13 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_cart_user_alter_cartitem_artwork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='data',
        ),
    ]
