name: Staging Deploy

on:
  push:
    branches:
      - staging

jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Heroku CLI
      run: curl https://cli-assets.heroku.com/install.sh | sh

    - name: Procfile Setup for Staging
      run: cp Procfile.staging Procfile

    - name: Login to Heroku Container Registry
      run: echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=_ --password-stdin registry.heroku.com

    - name: Build, Push and Release to Heroku (Staging App)
      run: |
        heroku container:push web --dockerfile Dockerfile.staging -a ${{ secrets.HEROKU_STAGING_APP_NAME }}
        heroku container:release web -a ${{ secrets.HEROKU_STAGING_APP_NAME }}
